var specs = [ { id : 0 , name : "Allergologue" },
{ id : 1 , name : "Anatomopathologiste" },
{ id : 2 , name : "Anesthésiste-réanimateur" },
{ id : 3 , name : "Angiologue" },
{ id : 4 , name : "Biologiste (Laboratoire d'analyse)" },
{ id : 5 , name : "Cardiologue" },
{ id : 6 , name : "Cardiologue pédiatrique" },
{ id : 7 , name : "Chirurgien cardiaque" },
{ id : 8 , name : "Chirurgien cardiaque pédiatrique" },
{ id : 9 , name : "Chirurgien esthétique et plastique" },
{ id : 10 , name : "Chirurgien maxillo-facial" },
{ id : 11 , name : "Chirurgien thoracique" },
{ id : 12 , name : "Chirurgien vasculaire" },
{ id : 13 , name : "Chirurgien viscérale" },
{ id : 14 , name : "Chirurgien viscérale pédiatrique" },
{ id : 15 , name : "Diabétologue" },
{ id : 16 , name : "Endocrinologue" },
{ id : 17 , name : "Gastro-entérologue" },
{ id : 18 , name : "Généticien" },
{ id : 19 , name : "Gérontologue - Gériatre" },
{ id : 20 , name : "Hématologue" },
{ id : 21 , name : "Médecin du sport" },
{ id : 22 , name : "Médecin du travail" },
{ id : 23 , name : "Médecin interniste " },
{ id : 24 , name : "Médecin légiste" },
{ id : 25 , name : "Médecin nucléaire" },
{ id : 26 , name : "Médecin physique et de réadaptation" },
{ id : 27 , name : "Neurochirurgien" },
{ id : 28 , name : "Neurologue" },
{ id : 29 , name : "Néonatologiste " },
{ id : 30 , name : "Néphrologue" },
{ id : 31 , name : "Néphrologue pédiatrique" },
{ id : 32 , name : "Oncologue - Cancerologue" },
{ id : 33 , name : "Oncologue médical" },
{ id : 34 , name : "Oto-rhino-laryngologiste" },
{ id : 35 , name : "Pneumologue" },
{ id : 36 , name : "Psychiatre" },
{ id : 37 , name : "Radiologue" },
{ id : 38 , name : "Radiothérapeute" },
{ id : 39 , name : "Rhumatologue" },
{ id : 40 , name : "Réanimateur Médical" },
{ id : 41 , name : "Réanimateur pédiatrique" },
{ id : 42 , name : "Sexologue" },
{ id : 43 , name : "Stomatologue" },
{ id : 44 , name : "Traumato-orthopédiste pédiatrique" },
{ id : 45 , name : "Traumatologue-orthopédiste" },
{id : 46 , name : "Urologue" },
{id : 47 , name : "Urologue pédiatrique" },
{id : 48 , name : "Phlébologue" },
{id : 49 , name : "Pédiatre" },
{id : 50 , name : "Médecin généraliste" },
{id : 51 , name : "Ophtalmologue" },
{id : 52 , name : "Dermatologue" },
{id : 53 , name : "Proctologue" },
{id : 54 , name : "Hépatologue" },
{id : 55 , name : "Algologue - Traitement de la douleur" },
{id : 56 , name : "Gynécologue" },
{id : 57 , name : "Endodontiste" },
{id : 58 , name : "Implantologiste " },
{id : 59 , name : "Orthodontiste" },
{id : 60 , name : "Parodontologiste" },
{id : 61 , name : "Pédodontiste" },
{id : 62 , name : "Dentiste" },
{id : 63 , name : "Occlusodontiste" },
{id : 64 , name : "Santé" },
{id : 65 , name : "Chiropracteur" },
{id : 66 , name : "Diététicien" },
{id : 67 , name : "Infirmier - Infirmière" },
{id : 68 , name : "Kinésithérapeute" },
{id : 69 , name : "Nutritionniste" },
{id : 70 , name : "Orthophoniste" },
{id : 71 , name : "Orthoptiste" },
{id : 72 , name : "Ostéopathe" },
{id : 73 , name : "Podologue" },
{id : 74 , name : "Psychologue" },
{id : 75 , name : "Psychomotricien"}];

module.exports  = specs;
